name: Tests workflow
on: 
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    
jobs:
  run_tests_and_push_to_codecov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [12.x, 14.x, 15.x, 16.x, 17.x, 18.x]
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build testing container
        run: docker build -t tests:${{ github.sha }} --build-arg SET_NODE_VERSION=$NODE_VERSION .
      - name: Invoke testing container
        run: docker run --network container:vault
         -e VAULT_ADDR=http://vault:8200
         -v $PWD/coverage:/app/coverage tests:${{ github.sha }} npm run coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)